version: '2'
services:
  nginx-serve:
    container_name: 'ttab-webserver'
    image: nginx:stable-alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./log/nginx:/var/log/nginx
      - ./setup/nginx/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - ttab-app
    depends_on:
      - ttab-app
  test-app:
    container_name: 'php7-maengron-app'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # - ./www:/var/www/html
      - ./log/app:/var/www/html/storage/logs
    command: bash -c "chmod 0777 -R /var/www/html/storage && php-fpm -F"
    expose:
      - 9000